version: '3'

services:
  todosDB:
    image: postgres:15.3
    container_name: inventarioDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=inventarioDBAdmin
      - POSTGRES_PASSWORD=1234567890
    volumes:
      - ./postgres:/var/lib/postgresql/data
